version: '3'
services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./dbpg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=crypto
      - POSTGRES_DB=crypto
      - POSTGRES_PASSWORD=crypto
    ports:
      - 5432:5432